### ISSUE TITLE
Class VS ID

### ISSUE THREAD

**Issue by mml1** [MParthum/prj-rev-bwfs-dasmoto#2]
Use classes for style changes that will be used by many elements and use ID for unique changes. In this project, it is best to use id for the changes to the h2 tags. 

So, instead of doing this:

```
    <div class="brushes">
        <h2>Brushes</h2>
```

Do this:
```
    <div>
        <h2 id="brushes">Brushes</h2>
```
Remember to change the CSS to target the id"

```
#brushes {
```
https://github.com/MParthum/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css#L19-L29

https://github.com/MParthum/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L13-L35

**Comment by MParthum** [comment]
added id's and updated style.css accordingly
