### ISSUE TITLE
Super large h1 tag

### ISSUE THREAD

**Issue by mml1** [MParthum/prj-rev-bwfs-dasmoto#3]
Your h1 tag is ginormous! h1, h2, h3, h4, h5, h6 tags have relative default stylings/User agent stylings for font size. Since you did not target the h1 tag directly, the default styling stayed, thus making your h1 tag super large. Be sure to go back and target the tag directly.

https://github.com/MParthum/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L9-L11

**Comment by MParthum** [comment]
Totally messed that up :D corrected this issue by targeting h1 directly in style.css
