### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [MParthum/prj-rev-bwfs-dasmoto#4]
[Meets Expectations] Excellent!

**Great work on:**

- easy to navigate project structure
- div usage
- alt tag usage
- relative links to both css and images
- descriptive labels
- inline element styling for price
- use of white space in code
- using a universal selector to change the font-family
- not repeating code

**Improve on:**

- class vs id usage
- adding comments
- adding alternative font families
- overwriting user agent/default stylings

**Future topics to research:**

- rem/em
- user agent stylings
- flexbox

**Comment by MParthum** [comment]
Thank you @mml1 for the review! I went back and updated the code based on your recommendations.
